// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDADbA91i5kmX4Nx3ZzGBXHzL1dXLkWZNs',
    appId: '1:332114580885:web:89313cda533e9663f2929c',
    messagingSenderId: '332114580885',
    projectId: 'cyclot-v1-4cf25',
    authDomain: 'cyclot-v1-4cf25.firebaseapp.com',
    storageBucket: 'cyclot-v1-4cf25.firebasestorage.app',
    measurementId: 'G-9G998KJ1WD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQFNx_UKk0X35hnQbSl5YjmqQZN8DvQu0',
    appId: '1:332114580885:android:312fd8f20f7782b9f2929c',
    messagingSenderId: '332114580885',
    projectId: 'cyclot-v1-4cf25',
    storageBucket: 'cyclot-v1-4cf25.firebasestorage.app',
  );
}
